#!/bin/bash

set -e

GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
RESET=`tput sgr0`

if git diff --cached --name-only | grep --quiet "shipping/proto/shipping.proto"
then
	echo "${YELLOW}Regenerating Shipping Protobufs${RESET}"
	make shipping-proto
else
	echo "${GREEN}Shipping Protobufs Unchanged${RESET}"
fi
if git diff --cached --name-only | grep --quiet "catalog/proto/catalog.proto"
then
	echo "${YELLOW}Regenerating Catalog Protobufs${RESET}"
	make catalog-proto
else
	echo "${GREEN}Catalog Protobufs Unchanged${RESET}"
fi
if git diff --cached --name-only | grep --quiet "store/proto/store.proto"
then
	echo "${YELLOW}Regenerating Store Protobufs${RESET}"
	make store-proto
else
	echo "${GREEN}Store Protobufs Unchanged${RESET}"
fi

make catalog-lint
make store-lint
make shipping-lint